### PR TITLE
Add generation of overlay for dts in Zephyr 

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**

### CODE REVIEW

**Comment by mithro** [comment]
Please rebase onto master so I can merge!

**Comment by mithro** [comment]
```
Using Zephyr SDK from: /home/travis/build/timvideos/litex-buildenv/build/zephyr_sdk
+set -e
+ZEPHYR_REPO=https://github.com/zephyrproject-rtos/zephyr
+ZEPHYR_REPO_BRANCH=master
+case $CPU in
+case "$CPU_VARIANT" in
+echo 'Zephyr needs a CPU_VARIANT set to at least '\''full'\'' for the support of '\''ecall'\'' instruction.'
Zephyr needs a CPU_VARIANT set to at least 'full' for the support of 'ecall' instruction.
+echo 'Supported variants: full, full+debug, linux.'
Supported variants: full, full+debug, linux.
+echo 'Currently selected variant: lite'
Currently selected variant: lite
+exit 1
```

**Comment by mithro** [comment]
Currently it breaks Zephyr on CI.

```
- make firmware (icebreaker base vexriscv.lite zephyr - zephyr)
---------------------------------------------
              Platform: icebreaker
                Target: base (default: base)
                   CPU: vexriscv.lite (default: lm32)
               Firmare: zephyr (default: firmware)
          Architecture: riscv32
Using Zephyr SDK from: /home/travis/build/timvideos/litex-buildenv/build/zephyr_sdk
+set -e
+ZEPHYR_REPO=https://github.com/zephyrproject-rtos/zephyr
+ZEPHYR_REPO_BRANCH=master
+case $CPU in
+case "$CPU_VARIANT" in
+echo 'Zephyr needs a CPU_VARIANT set to at least '\''full'\'' for the support of '\''ecall'\'' instruction.'
Zephyr needs a CPU_VARIANT set to at least 'full' for the support of 'ecall' instruction.
+echo 'Supported variants: full, full+debug, linux.'
Supported variants: full, full+debug, linux.
+echo 'Currently selected variant: lite'
Currently selected variant: lite
+exit 1
```

I think it would be good for Zephyr to work on the `lite` configuration. Options I can think of;
 * Add `ecall` instruction to `lite` variant.
 * Change CI to `full` -- possible be to big for the iCE40?
 * Make zephyr not require the `ecall` instruction.

**Comment by mateusz-holenko** [comment]
`ecall` is used in Zephyr to switch context in all RISC-V based platforms. Making Zephyr not to use it would require some architectural changes that would need to be accepted by the community. I personally don't think it's a good option.

Adding `ecall` to `lite` variant is an option, but it would make this variant bigger. From the perspective of the software that doesn't need this instruction it's an unnecessary change though. Perhaps introducing a new variant (called `zephyr` that would simply be `lite+ecall`) would be a solution?

For now I would go with switching CI to `full` variant and investigating a modified `lite` (or a new variant) in the meantime. What do you think about it @mithro?

**Comment by mithro** [comment]
What is the status of this pull request?

**Comment by mateusz-holenko** [comment]
We have proposed changes to VexRiscv `small` configuration in https://github.com/SpinalHDL/VexRiscv/pull/100 enabling `ecall` (that is required to run Zephyr), but this is sitll not merged.

We could always remove the commit changing required Zephyr configuration from this PR and merge DTS generation if you don't have any comments on that part.

**Comment by mateusz-holenko** [comment]
1. Removed the commit changing required CPU variant for Zephyr, leaving just the one adding DTS overlay generation.
1. Rebased on the newest master.

The Travis failed, but it looks like the problem is not in this PR as the same happened on c9e1c3b (the current master).

**Comment by mithro** [comment]
```
The following builds failed!
=============================================
icebreaker base vexriscv.lite zephyr
```

**Comment by mateusz-holenko** [comment]
The problem is that disabling the eth entry in the DTS file is not enough - the corresponding Kconfig option must be disabled as well.

I created a PR https://github.com/litex-hub/litex-renode/pull/20 adding the generation of config overlay file that should solve the problem.

**Comment by mithro** [comment]
https://github.com/litex-hub/litex-renode/pull/20 is now merged. Do we need to do anything more here?

**Comment by mateusz-holenko** [comment]
I bumped the litex-renode submodule and used the newly-merged feature (Kconfig overlay generation) to address the problem of platforms without ethernet controller.

Travis is failing, but it's not related to Zephyr anymore. I think it's good to merge.

**Comment by mithro** [comment]
I pushed https://github.com/timvideos/litex-buildenv/commit/8a7b8b53b4b8423fc159e250e143d11fa85b0f76 which should fix Travis.

**Comment by mithro** [comment]
Could you rebase?

**Pull request merged**
