### PR TITLE
Renode boot from flash

### PR DESCRIPTION
**Pull request by mateusz-holenko**
This PR adds two features to Renode emulation:

* support for shadow addresses,
* ability to boot from flash (no netboot needed).

### CODE REVIEW

**Comment by mithro** [comment]
Does renode have proper models of the nor spiflash parts?

**Comment by mateusz-holenko** [comment]
We have a model of Micron [MT25Q](https://www.micron.com/products/nor-flash/serial-nor-flash/mt25q).

In order to make things simple we usually model read-only XIP flashes as a memory that is loaded directly from Renode's monitor or script.

**Comment by mithro** [comment]
@mateusz-holenko - I think we want to support both modes? IE Writing to the SPI flash is a good thing you want to test.

**Comment by mateusz-holenko** [comment]
@mithro Sure.
I checked and this would require to add an spi flash controller (the one that does bitbanging) model to Renode, but it's not a problem.

Is there any firmware I could run to test if everything works as expected?
I found the ["driver" code](https://github.com/enjoy-digital/litex/blob/master/litex/soc/software/libbase/spiflash.c), but I see no place where any of `write_to_flash`, `write_to_flash_page` or `erase_flash_sector` is used.

**Comment by mateusz-holenko** [comment]
Since I couldn't find any firmware that writes to flash I decided to add a new command to LiteX BIOS ([PR](https://github.com/enjoy-digital/litex/pull/204) waiting).

I created a LiteX SPI flash controller model in Renode (currently under review) and once it's merged to master I will update this PR to use it in dynamically generated platform.

**Comment by mithro** [comment]
Blocked on https://github.com/conda/conda/issues/8843

**Comment by mateusz-holenko** [comment]
@mithro Travis is finally green. Is the current version fine for you?

**Pull request merged**
