### PR TITLE
WIP -- Modernize platforms + target files

### PR DESCRIPTION
**Pull request by mithro**
LiteX has change a lot since LiteX-BuildEnv was created. This pull request attempts to move towards more unification with upstream.

The major changes are;
 * Use new way to update `mem_map`.
 * Use `add_csr` + `add_interrupt` rather than previous dictionaries.
 * Use `add_wb_slave` + `add_memory_region` (cleanup usage of shadow_base and similar).

TODO Items;
 - [ ] Replace the `CRG` with new `S7PLL` and similar primitives (see https://github.com/litex-hub/litex-boards/blob/2ec6bc0bdc21b0c8afd9ca1fef0579f046c78fee/litex_boards/community/targets/mimas_a7.py#L26-L43)
 - [ ] Replace the `platforms` directory with importing from [`litex-boards`](https://github.com/litex-hub/litex-boards) and extending with the extra info.
 - [ ] Move a bunch of stuff into common functions (IE `add_spiflash`, `add_debug`, `add_linux`, etc)
 - [ ] Other stuff?

### CODE REVIEW

**Comment by rohitk-singh** [comment]
`netv2` and `neso` base targets are failing with (`lm32` CPU):
```
lm32-elf-ld: firmware.elf section `.bss' will not fit in region `sram'
lm32-elf-ld: region `sram' overflowed by 10136 bytes
/home/rohit/litex-buildenv-pr/firmware/Makefile:93: recipe for target 'firmware.elf' failed
```

**Comment by rohitk-singh** [comment]
Looks like all of the ISE based platforms' builda are failing at Map/PAR stage with similar message. Changes to clocking structure, or extra buffer in the path?
```
ERROR:Pack:1107 - Pack was unable to combine the symbols listed below into a
   single IOB component because the site type selected is not compatible. 

   Further explanation:
   The buffer "IBUFG" can not merge with signal "clk100." The signal has a
   NOMERGE property.
   Symbols involved:
        BUF symbol "IBUFG" (Output Signal = crg_clk100a)
        PAD symbol "clk100" (Pad Signal = clk100)


Mapping completed.
See MAP report file "top_map.mrp" for details.
Problem encountered during the packing phase.

Design Summary
--------------
Number of errors   :   1
Number of warnings :   0
```

image

**Comment by mithro** [comment]
The BOIS size issue has been reported at https://github.com/enjoy-digital/litex/issues/371

**Comment by mithro** [comment]
`nexys_video` currently failing with https://travis-ci.com/mithro/litex-buildenv/jobs/283126638
```
ERROR: [DRC UCIO-1] Unconstrained Logical Port: 1 out of 93 logical ports have no user assigned specific location constraint (LOC). This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all pin locations. This design will fail to generate a bitstream unless all logical ports have a user specified site LOC constraint defined.  To allow bitstream creation with unspecified pin locations (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks UCIO-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run.  Problem ports: user_btn5.
```

**Comment by mithro** [comment]
@enjoy-digital - Any idea what is causing this issue?

> `nexys_video` currently failing with https://travis-ci.com/mithro/litex-buildenv/jobs/283126638
> 
> ```
> ERROR: [DRC UCIO-1] Unconstrained Logical Port: 1 out of 93 logical ports have no user assigned specific location constraint (LOC). This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all pin locations. This design will fail to generate a bitstream unless all logical ports have a user specified site LOC constraint defined.  To allow bitstream creation with unspecified pin locations (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks UCIO-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run.  Problem ports: user_btn5.
> ```

**Comment by enjoy-digital** [comment]
@mithro: one the IOs is not correctly constrainted. You should have a warning before this Error that gives the IO's name.

**Comment by mithro** [comment]
> Looks like all of the ISE based platforms' builds are failing at Map/PAR stage with similar message. Changes to clocking structure, or extra buffer in the path?
> 
> ```
> ERROR:Pack:1107 - Pack was unable to combine the symbols listed below into a
>    single IOB component because the site type selected is not compatible. 
> 
>    Further explanation:
>    The buffer "IBUFG" can not merge with signal "clk100." The signal has a
>    NOMERGE property.
>    Symbols involved:
>         BUF symbol "IBUFG" (Output Signal = crg_clk100a)
>         PAD symbol "clk100" (Pad Signal = clk100)
> 
> 
> Mapping completed.
> See MAP report file "top_map.mrp" for details.
> Problem encountered during the packing phase.
> 
> Design Summary
> --------------
> Number of errors   :   1
> Number of warnings :   0
> ```
> 
> image

@enjoy-digital - Sorry I pointed you to the wrong error. I meant the one that @rohitk-singh pointed out with the `IBUFG`?

**Comment by enjoy-digital** [comment]
@mithro: could it be related to the fact that we now automatically add a keep attribute on all constrainted clock signals: https://github.com/enjoy-digital/litex/blob/master/litex/build/xilinx/ise.py#L264 and that it prevent some optimizations? This has been working fine with Vivado but maybe it's causing issues with ISE. If this is the issue, you could try to move the constraint to the clk pad instead of the buffered clock.

**Comment by mithro** [comment]
@mateusz-holenko -- IIRC you picked up these changes in another pull request right?

**Comment by mateusz-holenko** [comment]
Yes - changes from this branch in a slightly modified form has already been merged to master when bumping the LiteX submodule as a part of #348.

**Pull request closed without merging**
