### PR TITLE
iceFUN board

### PR DESCRIPTION
**Pull request by y2kbugger**
Tracking the initial porting of IceFun board, See #181 

Platform and targets based on ice40_hx8k_b_evnboard 

- [x] Add iceFun to travis
- [x] Add board to spreadsheet of supported boards
- [x] Conda package for iceFUNprog
- [x] Add to How to Ice40 guide https://github.com/timvideos/litex-buildenv/wiki/HowTo-FuPy-on-iCE40-Boards

I've moved the rest of the todos to issue #181, I'll follow up later with another PR for the rest, but I'd like to get this mainlined.

### CODE REVIEW

**Comment by mithro** [comment]
Looking good!

Can you add Travis build for this board?

**Comment by y2kbugger** [comment]
My builds all passed on https://github.com/timvideos/litex-buildenv/pull/186/commits/14730e525b92cc8d6efe153e5962163de1400e5f , but mor1kx.linux, vexriscv.lite are failing.

https://travis-ci.org/timvideos/litex-buildenv/builds/564425901?utm_source=github_status&utm_medium=notification

**Comment by mithro** [comment]
Just FYI - I rebased this onto master.

**Comment by y2kbugger** [comment]
This should be good to merge, I noticed a few of the travis build have been timing out but they are unrelated platforms. I've more remaining todo's to the #181 for tracking but I'd like to get this in master so I can work with the renode on getting renode working for icefun.

**Comment by mithro** [comment]
Great! Once Travis goes green I will merge....

**Pull request merged**
