### PR TITLE
WIP: Numato Elbert V2 support

### PR DESCRIPTION
**Pull request by mithro**

### CODE REVIEW

**Comment by ewen-naos-nz** [comment]
Current status:`

*   `elbertconfig.py` appears to work to program Numato demo 
*   `targets/elbertv2.py` is a plausible hand translation of Numato UCF file, but not tested
*   `platforms/elbertv2` is cargo cult hacked version of `targets/mimasv2` which probably will not work, and likely will not even parse, but is maybe 50% accurate

At this stage would probably benefit from someone with more experience with MiGen/MiSoC/litex looking at definition and figuring out how sane it is, before trying to test with actual hardware.  In particular it appears *every* other supported platform so far as external SDRAM, and Elbert v2 does not have external SDRAM (AFAIK) so it's not clear to me how directly any of the other platform definitions translate.

Branch pushed to GitHub at this stage as backup/to facilitate someone else looking at definitions.

**Comment by ewen-naos-nz** [comment]
With a few ugly hacks, just pushed, `make firmware` will produce a `firmware.elf`, etc, file -- the litex `flashboot()` function needed a dependency on main ram worked around (run in place, don't `memcpy()`), and HDMI / framebuffer / pattern needed stubbing out in order to avoid depending main ram (ideally these wouldn't even be built without main ram support available, as without main ram support there's not enough RAM for a framebuffer anwyay!).

Currently `linker.ld` assumes that most things will be relocated into main ram, which obviously is not possible on Elbert.  As a temporary work around there's a hand hacked linker.ld which has some approximation of relocations for run-in-place from SPI flash.  `make firmware` now completes, and the addresses used seem vaguely plausible, but it's both untested, and probably not 100% correct yet.

We will need a better way to generate/use a `linker.ld` file with/without main ram to handle this case.

**Comment by ewen-naos-nz** [comment]
`make gateware` currently fails, in ISE, due to design errors around the clocks.  That section is largely "as copied from Mimas v2" without editing properly, as I am unclear what should be in the PLL / clocks section.  Gateware failures below for reference.

<pre>
Annotating constraints to design from ucf file "top.ucf" ...
Resolving constraint associations...
Checking Constraint Associations...
WARNING:ConstraintSystem:137 - Constraint <NET "clk12" TNM_NET = "PRDclk12";>
   [top.ucf(21)]: No appropriate instances for the TNM constraint are driven by
   "clk12".

WARNING:ConstraintSystem:56 - Constraint <TIMESPEC "TSclk12" = PERIOD "PRDclk12"
   83.333 ns HIGH 50%;> [top.ucf(22)]: Unable to find an active 'TNM' or
   'TimeGrp' constraint named 'PRDclk12'.

WARNING:ConstraintSystem:191 - The TNM 'PRDclk12', does not directly or
   indirectly drive any flip-flops, latches and/or RAMS and cannot be actively
   used by the referencing Period constraint 'TSclk12'. If clock manager blocks
   are directly or indirectly driven, a new TNM constraint will not be derived
   even though the referencing constraint is a PERIOD constraint unless an
   output of the clock manager drives flip-flops, latches or RAMs. This TNM is
   used in the following user PERIOD specification:
   <TIMESPEC "TSclk12" = PERIOD "PRDclk12" 83.333 ns HIGH 50%;> [top.ucf(22)]

WARNING:ConstraintSystem:197 - The following specification is invalid because
   the referenced TNM constraint was removed:
   <TIMESPEC "TSclk12" = PERIOD "PRDclk12" 83.333 ns HIGH 50%;> [top.ucf(22)]

Done...

Checking expanded design ...
WARNING:NgdBuild:440 - FF primitive 'FDPE_5' has unconnected output pin
WARNING:NgdBuild:486 - Attribute "DIVIDE" is not allowed on symbol "BUFIO2" of
   type "BUFIO2".  This attribute will be ignored.
ERROR:NgdBuild:604 - logical block 'BUFIO2' with type 'BUFIO2' could not be
   resolved. A pin name misspelling can cause this, a missing edif or ngc file,
   case mismatch between the block name and the edif or ngc file name, or the
   misspelling of a type name. Symbol 'BUFIO2' is not supported in target
   'spartan3a'.
WARNING:NgdBuild:486 - Attribute "STARTUP_WAIT" is not allowed on symbol
   "crg_periph_dcm_clkgen" of type "DCM_CLKGEN".  This attribute will be
   ignored.
WARNING:NgdBuild:486 - Attribute "CLKFX_DIVIDE" is not allowed on symbol
   "crg_periph_dcm_clkgen" of type "DCM_CLKGEN".  This attribute will be
   ignored.
WARNING:NgdBuild:486 - Attribute "CLKFX_MULTIPLY" is not allowed on symbol
   "crg_periph_dcm_clkgen" of type "DCM_CLKGEN".  This attribute will be
   ignored.
WARNING:NgdBuild:486 - Attribute "CLKIN_PERIOD" is not allowed on symbol
   "crg_periph_dcm_clkgen" of type "DCM_CLKGEN".  This attribute will be
   ignored.
ERROR:NgdBuild:604 - logical block 'crg_periph_dcm_clkgen' with type
   'DCM_CLKGEN' could not be resolved. A pin name misspelling can cause this, a
   missing edif or ngc file, case mismatch between the block name and the edif
   or ngc file name, or the misspelling of a type name. Symbol 'DCM_CLKGEN' is
   not supported in target 'spartan3a'.
WARNING:NgdBuild:486 - Attribute "CLK_FEEDBACK" is not allowed on symbol
   "crg_pll_adv" of type "PLL_ADV".  This attribute will be ignored.
WARNING:NgdBuild:486 - Attribute "SIM_DEVICE" is not allowed on symbol
   "crg_pll_adv" of type "PLL_ADV".  This attribute will be ignored.
ERROR:NgdBuild:604 - logical block 'crg_pll_adv' with type 'PLL_ADV' could not
   be resolved. A pin name misspelling can cause this, a missing edif or ngc
   file, case mismatch between the block name and the edif or ngc file name, or
   the misspelling of a type name. Symbol 'PLL_ADV' is not supported in target
   'spartan3a'.

Partition Implementation Status
-------------------------------

  No Partitions were found in this design.

-------------------------------

NGDBUILD Design Results Summary:
  Number of errors:     3
  Number of warnings:  12
</pre>

**Comment by ewen-naos-nz** [comment]
FTR the litex BIOS `flashboot()` change is currently only at [ewen-naos-nz/litex on numato-elbert-v2]( https://github.com/ewen-naos-nz/litex/tree/numato-elbert-v2), but plausibly could be merged into litex once it's been tested to not affect systems with `MAIN_RAM_BASE` set.

**Comment by ewen-naos-nz** [comment]
Based on hints on #timvideos IRC, apparently Spartan 3A has no PLL, and instead has a [DCM (Digital Clock Manager)](https://www.xilinx.com/support/documentation/application_notes/xapp462.pdf) which needs completely different clock setup.  This means clock setup for Elbert v2 will need rewriting from scratch rather than copying from Mimas v2 (Spartan 6, with PLL).

**Comment by ewen-naos-nz** [comment]
Tested litex BIOS change to avoid copying to main ram when there is no main ram on Mimas v2 / Arty A7 -- appears to work on those existing platforms.  So created pull request -- https://github.com/enjoy-digital/litex/pull/55 -- for that bit of the change so we can depend on it more easily.

**Comment by ewen-naos-nz** [comment]
FTR summarising discussion at Hackfest: it seems like the low end Xilinx Spartan 3A on the Numato Elbert v2 (Xilinx XC3S50A) is too small to fit even a cut down lm32 soft CPU, which means that it may not be a viable target for litex, even after clock issues are resolved.  Ie, this might be a dead end, although possibly some of the work arounds to support "no external DRAM" might be useful for other dev boards with larger FPGA chips if they were cleaned up.

**Comment by mithro** [comment]
Yes, the "no external DRAM" is needed for a bunch of ice40, the pipistrello & probably others?

**Comment by mithro** [comment]
Gah, I did it again - I mean the Papillio not the Pipistrello....

**Comment by ewen-naos-nz** [comment]
@mithro IIRC the "no DRAM" development ended up being down elsewhere (by @rohitk-singh), so I don't think we're every going to merge this pull request as-is (and @rohitk-singh grabbed the relevant bits into his repo directly I believe).  So perhaps close this pull request to avoid clutter?

**Comment by rohitk-singh** [comment]
Yup, I had cherry-picked commits related to fixing the firmware when not using SDSoC. There are some changes to litex also (https://github.com/enjoy-digital/litex/pull/57) which haven't been merged yet (because haven't been tested yet).

**Comment by mithro** [comment]
Okay, closing this pull request.

**Pull request closed without merging**
