### PR TITLE
Bump submodules

### PR DESCRIPTION
**Pull request by mateusz-holenko**
This updates submodules to the newest version and fixes files broken in a process.

### CODE REVIEW

**Comment by mateusz-holenko** [comment]
@mithro Should I make a single commit with all the changes?

**Comment by mithro** [comment]
@mateusz-holenko Looks like CI is failing?

**Comment by mithro** [comment]
```
Errors from failures...
=============================================
./build/basys3_base_lm32/output.20190612-170404.log
---------------------------------------------
Traceback (most recent call last):
  File "./make.py", line 164, in <module>
    main()
  File "./make.py", line 123, in main
    soc = get_soc(args, platform)
  File "./make.py", line 56, in get_soc
    exec("from targets.{}.{} import SoC".format(args.platform, args.target.lower(), args.target), globals())
  File "<string>", line 1, in <module>
  File "/home/travis/build/timvideos/litex-buildenv/targets/basys3/base.py", line 52, in <module>
    class BaseSoC(SoCCore):
  File "/home/travis/build/timvideos/litex-buildenv/targets/basys3/base.py", line 57, in BaseSoC
    csr_map_update(SoCCore.csr_map, csr_peripherals)
  File "/home/travis/build/timvideos/litex-buildenv/targets/utils.py", line 10, in csr_map_update
    for v, n in enumerate(csr_peripherals, start=max(csr_map.values()) + 1)))
ValueError: max() arg is an empty sequence
---------------------------------------------
```

**Comment by mateusz-holenko** [comment]
I know, I'm working on it.

**Comment by mateusz-holenko** [comment]
@mithro Could you take a look at Travis logs? Now both this PR and #147 fail in the same way and it looks like some infrastructural problem.

What is the source of `TRAVIS_COMMIT` variable in `.travis/fixup-git.sh`?

**Comment by mithro** [comment]
@mateusz-holenko You just need to push a new commit.

**Comment by mateusz-holenko** [comment]
@mithro The CI is finally green, but I had to modify the code in many different places. Please take a look if my "fixes" make sense.

**Pull request merged**
