### PR TITLE
minerva support

### PR DESCRIPTION
**Pull request by futaris**

### CODE REVIEW

**Comment by futaris** [comment]
I tested TARGET=base and TARGET=net with renode. It runs (after you modify the renode script and supply a Renode platform).

**Comment by mithro** [comment]
You'll need to rebase to make Travis work.

**Comment by mithro** [comment]
FYI - I added minerva to the Travis CI and into the `./scripts/download-env.sh` that you have missed.

Will merge when it goes green.

**Comment by mithro** [comment]
Pull Request #130 - minerva support - #237.40 passed
\o/

**Pull request merged**
